### ISSUE TITLE
Add kubetos

### ISSUE THREAD

**Issue by philippemerle** [philippemerle/tosca-implementation-landscape#16]
kubetos is a TOSCA framework to deploy Kubernetes developed by @Shishqa and available at https://github.com/Shishqa/kubetos.

**Comment by Shishqa** [comment]
Thank you for mentioning!

There is also an orchestrator [clouni](https://github.com/ispras/clouni) developed by [ISPRAS](https://github.com/ispras), we would be happy for you to have a look at it too

**Comment by philippemerle** [comment]
@Shishqa you are welcome to open an issue for clouni.

Please provide me information describing clouni such as
* TOSCA definition versions supported
* Target environments, e.g. any cloud or a specific provider
* Usage, e.g. CLI, Webapp, SaaS, etc.
* Nature, e.g. open source vs commercial, academia vs company, etc.
* Implementation languages, e.g. Python, Go, Java, etc.
* Links, e.g. website, github, others
* Is clouni using other TOSCA implementations? e.g. OpenStack TOSCA Parser, Puccini, xOpera, etc.
* Any other key information

I will be happy to include clouni in the TOSCA implementation landscape.
